### PR TITLE
Fix Jasmine Unit Test errors

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| New feature?     | no
| BC breaks?       | no
| Deprecations?    | no
| New tests added? | not needed
| Fixed tickets    | 
| License          | MIT

### Description

Fix a bunch of unit tests that were failing upon running `npm run build`. Now everything builds fine again.

--

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
I had to fix also the Travis build. Not sure why, but you were still using NodeJS 0.10, while it's very safe to use the latest LTS. I hope it's fine for you.

**Comment by julianxhokaxhiu** [comment]
@j0k3r Fixed conflicts, you can merge it now if you want.

**Comment by j0k3r** [comment]
You remove the change of nodejs version?

**Comment by julianxhokaxhiu** [comment]
Yeah, I kept your choice in master, in order to avoid conflicts while merging :)

**Pull request merged**
