### PR TITLE
#886 - Cannot press space when i'm with the cursor at the end of line

### LINKED ISSUE #886: Cannot press space when i'm with the cursor at the end of line
I think that is a bug added on release 5.10.0. Now i'm not be able to add a space when the cursor is on the end of line. This bug was added by this condition: 

if ((textContent[caretPositions.left - 1] === undefined) || (textContent[caretPositions.left - 1] === ' ') || (textContent[caretPositions.left] === undefined)) ...

on the function 'function handleDisableExtraSpaces(event)'

### PR DESCRIPTION
**Pull request by patrinhani-ciandt**
Fix #886

### CODE REVIEW

**Comment by j0k3r** [comment]
This doesn't fix the issue. It remove ability to **not** have multiple spaces.

**Comment by patrinhani-ciandt** [comment]
I've tested here and it works, let's you add only one space at the end if you add something on the paragraph

**Comment by j0k3r** [comment]
You're right, I've made a bad copy/paste.
I've tried to add some tests about that but didn't get results I wanted.

```js
        it('should allow one space at the end of a line when disableExtraSpaces options is true', function () {
            this.el.innerHTML = '<p>lorem ipsum</p>';

            var editor = this.newMediumEditor('.editor', { disableExtraSpaces: true }),
                evt;

            placeCursorInsideElement(editor.elements[0].getElementsByTagName('p')[0], 1);

            evt = prepareEvent(editor.elements[0], 'keydown', {
                keyCode: MediumEditor.util.keyCode.SPACE
            });

            spyOn(evt, 'preventDefault').and.callThrough();

            firePreparedEvent(evt, editor.elements[0], 'keydown');

            expect(evt.preventDefault).not.toHaveBeenCalled();
        });

        it('should prevent more spaces from being inserted at the end of a line when disableExtraSpaces options is true 3', function () {
            this.el.innerHTML = '<p>lorem ipsum               </p>';

            var editor = this.newMediumEditor('.editor', { disableExtraSpaces: true }),
                evt;

            placeCursorInsideElement(editor.elements[0].getElementsByTagName('p')[0], 1);

            evt = prepareEvent(editor.elements[0], 'keydown', {
                keyCode: MediumEditor.util.keyCode.SPACE
            });

            spyOn(evt, 'preventDefault').and.callThrough();

            firePreparedEvent(evt, editor.elements[0], 'keydown');

            expect(evt.preventDefault).toHaveBeenCalled();
        });
```

First one shouldn't pass without your change but pass with your change.
Second one should pass with or without your change.

But the second one always fail for me.
Any idea?

**Comment by patrinhani-ciandt** [comment]
Thinking ....

**Comment by patrinhani-ciandt** [comment]
Is it not because the point that you are positioning the cursor ?

**Comment by j0k3r** [comment]
Maybe, I've no idea ..

**Comment by daviferreira** [comment]
The problem is with phantomjs, it passes on the browser. I think phaton ignroes white spaces when creating the range. If you add a `<br />` here it passes:

` this.el.innerHTML = '<p>lorem ipsum               <br /></p>';`

**Comment by j0k3r** [comment]
@daviferreira yay :rocket:

**Comment by j0k3r** [comment]
@patrinhani-ciandt I'm going to merge your stuff and make a new PR with tests.

**Comment by patrinhani-ciandt** [comment]
@j0k3r awesome man ... thank's @daviferreira for your help !

**Pull request merged**
