### PR TITLE
Fix #1173: When caret is at the end of Div and you press enter, create p not a Div

### LINKED ISSUE #1173: when caret is at the end of 'Div'  and you press enter, create paragraph, not another 'Div'
Description:
when you have div with the list of classes and styles and When you place a caret at the end of that div and press enter, a new div tag is created with same all the list of classes and same style attribute instead of a plain paragraph. This is not a standard behavior. When you do the same with other block elements (h1, h2...) you will get a paragraph as expected. For some reason, this doesn't work with 'div'.

### PR DESCRIPTION
**Pull request by durgeshahire4**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| New tests added? | yes |
| Fixed tickets | #1173 |
| License | MIT |

### CODE REVIEW

**Comment by durgeshahire4** [comment]
The build is failing because of another issue. can anyone check this out? and resolve my issue.

**Comment by nmielnik** [comment]
@durgeshahire4 looks to be some code style issues, could you fix those and try again?

https://travis-ci.org/yabwe/medium-editor/builds/151221140

**Comment by durgeshahire4** [comment]
@nmielnik  Can you please check 
https://travis-ci.org/yabwe/medium-editor/builds/151506678
m not able to resolve this one

**Comment by nmielnik** [comment]
@durgeshahire4 looks like there's still a test failing, you can always run the tests locally by just running `grunt` from the root medium-editor folder.

**Comment by nmielnik** [comment]
this PR seems to contain nothing but a test case...closing it

**Pull request closed without merging**
