### PR TITLE
Editing the documetation/read-me #1276

### PR DESCRIPTION
**Pull request by msaiyaff**
| Q                | A
| ---------------- | ---
| Bug fix?         | no
| New feature?     | no
| BC breaks?       | no
| Deprecations?    | no
| New tests added? | no
| Documentation | Yes
| Fixed tickets    | comma-separated list of tickets fixed by the PR, if any
| License          | MIT

### Description

[Description of the bug or feature]

--

#### Please, don't submit `/dist` files with your PR!
_Removed the dist folder as it's mentioned above_

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you please just update the readme file?

**Comment by msaiyaff** [comment]
@j0k3r Done. Thanks for it.

**Comment by j0k3r** [comment]
Sorry but nothing changed.

**Comment by msaiyaff** [comment]
@j0k3r I mean I have edited the readme just there itself. I think you can close this PR without merging.
Refer to this - https://github.com/yabwe/medium-editor/pull/1286

**Comment by j0k3r** [comment]
Okay

**Pull request closed without merging**
