### PR TITLE
Add option to disable tab key.

### PR DESCRIPTION
**Pull request by geoffliu**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| New tests added? | not needed |
| Fixed tickets | none |
| License | MIT |
### Description

Hey all. This is something we need for our current project, don't know if there's any interest in accepting upstream. 

cheers,
Geoff
##

### CODE REVIEW

**Comment by j0k3r** [comment]
Interesting.
Could you fix the style issue and maybe add some tests about that?

**Comment by geoffliu** [comment]
@j0k3r I don't have a whole lot of bandwidth at present, but will add tests when I can.

**Comment by nmielnik** [comment]
@geoffliu correct me if I'm wrong, but if I was summarizing the goal of this PR it would be:

When the user presses <kbd>tab</kbd> allow the browser's default behavior to occur (moving focus to another element?).  Don't indent text within a `<pre>` and don't change indentation level of '<li>` elements.

Is that right?

**Comment by geoffliu** [comment]
@nmielnik Yes that's correct.

**Comment by nmielnik** [comment]
Ok great, makes sense.  I think the name `disableTab` is a bit-misleading, I had thought it would actually prevent tab from doing anything and it wasn't until I read the code that I realized what it was doing.

Could you rename this to something like 'defaultTabBehavior' (default value is `false`)?  Something to say that the editor won't do anything when the user pushes <kbd>tab</kbd> but the default browser behavior will still happen?

And like @j0k3r mentioned, adding some tests will also help clarify what should happen so that make sure this feature is maintained and not broken in the future.

Thanks for this!

**Comment by geoffliu** [comment]
Ah I see. I was just mirroring the naming of `disableReturn`  and `disableDoubleReturn`. Do we not want to keep them consistent? 

And yes, absolutely agree with tests, will do that as soon as I get the bandwidth.

**Comment by nmielnik** [comment]
`disableReturn`, `disableDoubleReturn`, `disableExtraSpaces`, and `disableEditing` are all options that attempt to disable some functionality from the browser.  In this case, the editor has code that will attempt to add on top of the browser's functionality (doing some indentation).  

So, I think of the option you're adding as a bit different, since it will be turning off some extra code that is added by medium-editor, instead of turning off something the browser does by default.  But, that's just my opinion.

**Comment by nmielnik** [comment]
@geoffliu another option to represent this feature is by creating a `tabIndent` option.  This option would be true by default, but if you set it to false then you get the behavior that you've created in this PR. Just another way to think about it.

**Comment by mkawczynski07** [comment]
@geoffliu if u want "disable tab key":

```    
   this.mediumEditor.subscribe('editableKeydownTab', e => {
      e.preventDefault();
      e.stopPropagation();
    });
```

**Pull request closed without merging**
