### PR TITLE
Issue 824 Remove leading and trailing whitespaces from links

### PR DESCRIPTION
**Pull request by pranthiks**
Fix https://github.com/yabwe/medium-editor/issues/824

### CODE REVIEW

**Comment by j0k3r** [comment]
Great! Thanks for the PR.
Could you remove the dist files from your PR (as specified in our [CONTRIBUTING file](https://github.com/yabwe/medium-editor/blob/master/CONTRIBUTING.md))?

**Comment by pranthiks** [comment]
Sure thing, sorry I missed that part.

Should I undo the changes to the dist file as another commit to this branch?

**Comment by j0k3r** [comment]
Yes you can !

**Comment by nmielnik** [comment]
I believe this has been fixed via #838

**Pull request closed without merging**
