### PR TITLE
Fix font-awesome.css link in demo/auto-link.html

### PR DESCRIPTION
**Pull request by anilmaurya**
screen shot 2015-10-09 at 10 28 35 pm

### CODE REVIEW

**Comment by daviferreira** [comment]
This is actually on purpose, to make use of the current protocol. If we are going to change it, we need to change on all demo files.  But I'm not sure about it :)

**Comment by anilmaurya** [comment]
@daviferreira I didn't understand your point. Is this working for you ? are you serving demo files with http server ?

**Comment by nmielnik** [comment]
@daviferreira we use a completely different file for the demo page that we host right?  If we leave that hosted page using the relative protocol URLs, but change the internal demo files within the repo to use a hard-coded protocol, we should still be ok right?

I might be forgetting another reason why we changed the urls to be relative-protocol in the actual source code...

**Comment by daviferreira** [comment]
@anilmaurya yeap, actually I always use https://simbco.github.io/httpster/ :)

But I agree, let's change it. If you could update this PR changing al demo files please.

**Comment by anilmaurya** [comment]
@daviferreira sure , I will update this PR with all demo files change.

**Comment by anilmaurya** [comment]
@daviferreira only 2 other demo files had this issue. Updated PR

**Comment by daviferreira** [comment]
Thanks!

**Pull request merged**
