### PR TITLE
stickyTopOffset option added

### PR DESCRIPTION
**Pull request by vied12**
I needed this option in order to keep on the screen a sticky toolbar when I have a static page header.

### CODE REVIEW

**Comment by j0k3r** [comment]
Interesting. Can you provide a screenshot before / after of your toolbar? I'm just curious to see the difference.

**Comment by vied12** [comment]
## Before
before
## After
after

**Comment by j0k3r** [comment]
Ok thanks !

**Comment by vied12** [comment]
You are welcome :bowtie:

**Pull request merged**
