### PR TITLE
Link Validation - Allow More Schemes

### PR DESCRIPTION
**Pull request by ppoulsen**
This uses a far more liberal regular expression when `anchor.linkValidation === true`. Before, `http://`, `https://`, `ftp://`, `ftps://`, `rtmp://`, `rtmpt://`, and `mailto:` were the only allowed schemes (and `mailto:` could be anywhere in the URL). Now, any set of alphabetical characters before `://` is considered valid, as well as the protocol-relative `//` and the external schemes `mailto:`, `tel:`, and `maps:`. The regular expression is also now case-insensitive.

No additional tests added to the existing tests [for adding http:// when no scheme provided](https://github.com/yabwe/medium-editor/issues/873#issuecomment-155103024) and [for not changing when valid](https://github.com/yabwe/medium-editor/blob/bdd19e3153bf07b1434df8506d2aee77e04d11c3/spec/anchor.spec.js#L203).

**Further Reading**
[Generic scheme regular expression retrieved from here.](http://stackoverflow.com/a/19709846)
[Gist on external schemes.](https://gist.github.com/jonathantneal/6301455)

### CODE REVIEW

**Comment by nmielnik** [comment]
@ppoulsen could you add a test to verify that some of the urls you're supporting will make it through the `checkLinkFormat()` check?  You could add unit tests that call `checkLinkFormat()` directly with various schemes, or you can add more tests similar to [this test](https://github.com/yabwe/medium-editor/blob/master/spec/anchor.spec.js#L186).

**Comment by nmielnik** [comment]
Apologies @ppoulsen but it looks like #877 conflicted with your changes.  I know your PR came first, but the other PR was ready to go (with a test) so it got merged in first.  If you could fix the merge conflict and add a couple tests, we'll make sure this gets in quickly.

Thanks again for the submission.

**Comment by ppoulsen** [comment]
@nmielnik will do!

**Comment by ppoulsen** [comment]
@nmielnik Alright, should be good to go!

**Comment by nmielnik** [comment]
Awesome, thanks @ppoulsen !

**Pull request merged**
