### PR TITLE
#1127 | Placeholder is visible when only empty table is in Editor.

### PR DESCRIPTION
**Pull request by durgeshahire4**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| New feature?     | no
| BC breaks?       | no
| Deprecations?    | no
| New tests added? | not needed
| Fixed tickets    |  1127
| License          | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
How does it work with medium-editor-tables?

**Comment by durgeshahire4** [comment]
didn't get your question. Can you please elaborate?

**Comment by j0k3r** [comment]
Have you tried your behavior with https://github.com/yabwe/medium-editor-tables ?

**Comment by durgeshahire4** [comment]
Yes, i ma using same extension

**Comment by durgeshahire4** [comment]
@j0k3r Is this Bug or existing functionality?

**Comment by j0k3r** [comment]
Good question :)

**Comment by nmielnik** [comment]
@durgeshahire4 this looks good, could you add a test to verify this?  There are a bunch of very similar tests that you can use as a template [here](https://github.com/yabwe/medium-editor/blob/master/spec/placeholder.spec.js#L26-42)

**Comment by durgeshahire4** [comment]
@j0k3r @nmielnik i have updated the test cases, Have a look

**Comment by j0k3r** [comment]
Looks ok to me 👍

**Comment by nmielnik** [comment]
All the tests passed in SauceLabs: https://travis-ci.org/yabwe/medium-editor/builds/139188607

**Comment by durgeshahire4** [comment]
Thanks

**Pull request merged**
