### PR TITLE
single enter double enter [WIP]🚧

### PR DESCRIPTION
**Pull request by rishijain**
Pressing `ENTER` insert a `<br>` tag, and pressing `ENTER` x 2 inserts a `<p>` tag.

### CODE REVIEW

**Comment by whatthewhat** [comment]
Hi, this would be a very nice feature to have!
Is this something that's in active development? Anything I can do to help out? :)

**Comment by rishijain** [comment]
@whatthewhat  Feel free to work on this. I haven't been able to work on this for a while now.

**Comment by whatthewhat** [comment]
Cool, I'll have some time for it this weekend

**Comment by whatthewhat** [comment]
Hmm, just realised this might not do what I thought it did..

What is the reasoning behind not triggering the new behaviour at the end of the line?
```
//if cursor is at the end of line or
//if cursor is at the beginning of line, behaviour of enter should not change
```

This is pretty much the majority of our use case :)

**Comment by rishijain** [comment]
I am closing this now. Haven't worked on it for the longest time. Also it may hold up someone who wish to fix the issue.

**Pull request closed without merging**
