### PR TITLE
handle new google docs font weights

### PR DESCRIPTION
**Pull request by nelsonpecora**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| New feature?     | no
| BC breaks?       | no
| Deprecations?    | no
| New tests added? | yes
| Fixed tickets    | #1167
| License          | MIT

### Description

Added support for _numbered_ font weights when pasting from Google Docs, as it looks like they switched to those sometime in the past month or so.

--

### CODE REVIEW

**Comment by nelsonpecora** [comment]
This could probably do with a test, but when I added one it started breaking unrelated tests (specifically toolbar positioning). Thoughts?

**Comment by j0k3r** [comment]
Well, add a new tests and we'll see how Travis is going about that

**Comment by nelsonpecora** [comment]
Roger that!

**Comment by nelsonpecora** [comment]
Well ok then. ¯\_(ツ)_/¯

**Comment by j0k3r** [comment]
:+1:

**Pull request merged**
