### PR TITLE
CSS/SASS refactor

### PR DESCRIPTION
**Pull request by daviferreira**
*now targeting the v5 branch*

* `medium-element` becomes `medium-editor-element`
* `sticky-toolbar` becomes `medium-editor-sticky-toolbar`
* `stalker-toolbar` becomes `medium-editor-stalker-toolbar`

The rest was mainly creating components and organizing editor/toolbar components. There is more room for improvement, but this is a start.

### CODE REVIEW

**Comment by j0k3r** [comment]
You can remove all *deprecated* stuff since you are targeting the v5 branch.

**Comment by daviferreira** [comment]
True that :beers:

**Comment by j0k3r** [comment]
@daviferreira You need to rebase your branch agaisnt the v5 so we can merge it.

Except if @nchase has something more to check? :smile:

**Comment by daviferreira** [comment]
@j0k3r done

**Comment by nchase** [comment]
looks good to me.

1. is this still targeting 5.0.0?
2. made #672 as a follow-up to this. that's a task I'd like to take on.

**Pull request merged**
