### PR TITLE
New anchor preview option to show when toolbar is visible

### PR DESCRIPTION
**Pull request by gerherz**
New option as discussed here: https://github.com/yabwe/medium-editor/issues/825

### CODE REVIEW

**Comment by nmielnik** [comment]
Awesome, the change looks great!  Were you able to verify that this fixed #825 for your use case?

2 Things:
1. Could you add a couple tests?
2. Could you update the documentation (README.md & OPTIONS.md) to describe the few option?

Thanks again!

**Comment by gerherz** [comment]
Yes, my use case is fixed. I have just updated the documentation on both files.

As for the tests, I couldn't find a test that checks that the preview is not visible when the toolbar is. Is there any, so that I can work on top of it?

**Comment by nmielnik** [comment]
You can see a test case that is similar to what you'd be testing [here](https://github.com/yabwe/medium-editor/blob/master/spec/anchor-preview.spec.js#L220-L236) (although the description of the test case isn't quite accurate).  You can also check `toolbar.spec.js` for cases that check for the existence/visibility of the toolbar.

**Comment by gerherz** [comment]
Thanks, I've added two tests. Please take a look at them to make sure that they are OK.

**Comment by nmielnik** [comment]
Awesome, thanks @gerherz !

**Pull request merged**
